<a href="https://colab.research.google.com/github/IvanLuozZZ/Exercises/blob/master/tensor_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[2.9220e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.9985, 0.8606, 0.7369],
        [0.7364, 0.3102, 0.7286],
        [0.3030, 0.5638, 0.8658],
        [0.2022, 0.1975, 0.4250],
        [0.4859, 0.8426, 0.5150]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)
print(x.dtype)

tensor([5.5000, 3.0000])
torch.float32


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.7463, -0.0276,  0.7660],
        [ 0.7256, -0.9253, -0.2974],
        [ 0.8405,  0.4389,  0.1309],
        [ 0.6047, -0.1183,  0.2859],
        [ 0.0490,  1.1665,  0.2054]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.1899,  0.6520,  1.5298],
        [ 1.5472, -0.1683,  0.2503],
        [ 1.0169,  1.3854,  0.5301],
        [ 1.2417,  0.4163,  0.9290],
        [ 0.9746,  1.6734,  0.6037]])


In [11]:
print(torch.add(x, y))

tensor([[-0.1899,  0.6520,  1.5298],
        [ 1.5472, -0.1683,  0.2503],
        [ 1.0169,  1.3854,  0.5301],
        [ 1.2417,  0.4163,  0.9290],
        [ 0.9746,  1.6734,  0.6037]])


In [12]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.1899,  0.6520,  1.5298],
        [ 1.5472, -0.1683,  0.2503],
        [ 1.0169,  1.3854,  0.5301],
        [ 1.2417,  0.4163,  0.9290],
        [ 0.9746,  1.6734,  0.6037]])


In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.1899,  0.6520,  1.5298],
        [ 1.5472, -0.1683,  0.2503],
        [ 1.0169,  1.3854,  0.5301],
        [ 1.2417,  0.4163,  0.9290],
        [ 0.9746,  1.6734,  0.6037]])


In [16]:
print(x)
print(x[:, 1])
print(x[:, 0])
print(x[1, 1])

tensor([[-0.7463, -0.0276,  0.7660],
        [ 0.7256, -0.9253, -0.2974],
        [ 0.8405,  0.4389,  0.1309],
        [ 0.6047, -0.1183,  0.2859],
        [ 0.0490,  1.1665,  0.2054]])
tensor([-0.0276, -0.9253,  0.4389, -0.1183,  1.1665])
tensor([-0.7463,  0.7256,  0.8405,  0.6047,  0.0490])
tensor(-0.9253)


In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x)
print(y)
print(z)
print(x.size(), y.size(), z.size())

tensor([[ 0.4298, -0.8082, -1.0828, -0.4799],
        [ 0.5651,  0.5637,  0.2782,  0.7420],
        [ 1.1027,  0.8154,  0.5115, -1.0108],
        [ 0.3033,  0.2517,  0.2312,  0.3712]])
tensor([ 0.4298, -0.8082, -1.0828, -0.4799,  0.5651,  0.5637,  0.2782,  0.7420,
         1.1027,  0.8154,  0.5115, -1.0108,  0.3033,  0.2517,  0.2312,  0.3712])
tensor([[ 0.4298, -0.8082, -1.0828, -0.4799,  0.5651,  0.5637,  0.2782,  0.7420],
        [ 1.1027,  0.8154,  0.5115, -1.0108,  0.3033,  0.2517,  0.2312,  0.3712]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4757])
-0.4756980538368225


In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [24]:
# 当GPU可用时,可以运行以下代码
# 使用`torch.device`来将tensor移入和移出GPU
if torch.cuda.is_available():
    device = torch.device("cuda")      # a CUDA device object
    y = torch.ones_like(x, device=device) # 直接在GPU上创建tensor
    x = x.to(device)             # 或者使用`.to("cuda")`方法
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # `.to`也能在移动时改变dtype

tensor([0.5243], device='cuda:0')
tensor([0.5243], dtype=torch.float64)
